import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  en: {
    translation: {
      "title": "Tempus Electrica",
      "description": "Tempus Electrica is a service that allows you to monitor pricing between Fixed and Exchange electricity",
      "info1": "In the service, you can view your own consumption and its cost by <b>uploading your own electricity consumption file</b><br />",
      "info2": "We will tell you which one suits you better, <br /><b>Fixed or Exchange electricity</b>",
      "info3": "Alternatively, you can also estimate your electricity consumption with the <b>calculator</b>",
      "uploadFile": "Upload consumption file",
      "estimateConsumption": "Estimate your electricity consumption",
      "instructions": "Instructions",
      "instructionsTitle": "Instructions",
      "step1": "Go to the <a href=\"#\" onClick=\"(event) => { event.preventDefault(); window.open('https://oma.datahub.fi/#/login?returnUrl=%2F', '_blank'); }\"> Fingrid customer portal </a> and log in",
      "step1ImgAlt": "Fingrid login",
      "step2": "Select the property you want to monitor the electricity consumption for",
      "step2ImgAlt": "Fingrid Energy Report",
      "step3": "Select <b>Energy Reporting</b> and go to the <b>Download Information</b> window",
      "step3ImgAlt": "Fingrid Energy Report",
      "step4": "Select the desired time period and property",
      "step4ImgAlt": "Fingrid Energy Report",
      "step5": "Press the <b>Download</b> button. This will download the <b>electricity consumption file</b> to your device, which you can upload to the calculator",
      "step6": "<b>Do not make any changes</b> to the file, as it may affect the calculation!",
      "backButton": "Back to calculator",
      "compareElectricityPrice": "Compare Electricity Price",
      "introText1": "In the service, you can view your electricity consumption and its cost by uploading your own electricity consumption file.",
      "introText2": "Download your electricity consumption file from ",
      "setFixedPrice": "Set Fixed Price",
      "uploadAndViewResults": "Upload your file and view the results ",
      "uploadAndViewResultsBold": " Month, week, and day level!",
      "fixedPrice": "Fixed Price",
      "enterFixedPrice": "Enter fixed price",
      "csvFile": "Consumption file(.csv)",
      "showSpotPrice": "Show Spot Price",
      "showFixedPrice": "Show Fixed Price",
      "showConsumption": "Show Consumption",
      "timePeriod": "Time Period",
      "day": "Day",
      "week": "Week",
      "month": "Month",
      "loading": "Loading",
      "submit": "Submit",
      "errorFetchingData": "Error fetching data. Please try again.",
      "pleaseFillRequiredFields": "Please fill in all required fields.",
      "previous": "Previous",
      "next": "Next",
      "previousYear": "Previous Year",
      "nextYear": "Next Year",
      "invalidDate": "Invalid date format",
      "readInstructions": "Read download instructions",
      "here": "here",
      "loadingAnimation": "Loading Animation",
      "Fingridcustomerportal": "Fingrid customer portal",
      "prevPeriod": "Previous",
      "nextPeriod": "Next",
      "prevYear": "Previous Year",
      "showDaily": "Show Daily",
      "showWeekly": "Show Weekly",
      "showMonthly": "Show Monthly",
      "results": "Results",
      "cheaperOption": "The cheaper option for you is",
      "spotElectricity": " Spot electricity",
      "fixedElectricity": " Fixed electricity",
      "priceDifference": "Price difference",
      "consumption": "Consumption",
      "spotElectricityPrice": "Spot electricity price for consumption",
      "fixedElectricityPrice": "Fixed electricity price for consumption",
      "time": "Time Period",
      "priceConsumption": "Price / Consumption",
      "totalConsumption": "Total consumption",
      "timeperiodinfo": "Based on your consumption file over a period of time",
    
      "ChartSpotPrice": "Spot Price",
      "Price/Consumption": "Price / Consumption",
      "ChartMonth": "Month",
      "ChartTime": "Time",
      "unit": " (cents/kWh)",
      "DataResource": "Recourse of spot price data"
    }
  },
  fi: {
    translation: {
      "title": "Tempus Electrica",
      "description": "Tempus Electrica on palvelu, joka mahdollistaa hinnoittelun seurannan Kiinteän ja Pörssi sähkön välillä",
      "info1": "Palvelussa voit tarkastella omaa kulutustasi ja sen hintaa <br /> <b>lataamalla oman sähkönkulutus-tiedoston</b>",
      "info2": "Me kerromme sinulle <br /> kumpi sopii sinulle paremmin, <br /><b>Kiinteä vai Pörssi sähkö</b>",
      "info3": "Vaihtoehtoisesti voit myös arvioida sähkönkulutustasi <br />  <b>laskurin avulla</b>",
      "uploadFile": "Lataa kulutustiedosto",
      "estimateConsumption": "Arvioi sähkönkulutustasi",
      "instructions": "Ohjeet",
      "instructionsTitle": "Ohjeet",
      "step1": "Siirry <a href=\"#\" onClick=\"(event) => { event.preventDefault(); window.open('https://oma.datahub.fi/#/login?returnUrl=%2F', '_blank'); }\"> Fingrid asiakas portaaliin </a> ja kirjaudu sisään",
      "step1ImgAlt": "Fingrid kirjautuminen",
      "step2": "Valitse kiinteistö, jonka sähkönkulutusta haluat seurata",
      "step2ImgAlt": "Fingrid Energiaraportti",
      "step3": "Valitse <b>Energy Reporting</b> ja siirry <b>Download Information</b> ikkunaan",
      "step3ImgAlt": "Fingrid Energiaraportti",
      "step4": "Valitse haluamasi aikaväli ja kiinteistö",
      "step4ImgAlt": "Fingrid Energiaraportti",
      "step5": "Paina <b>Download</b> painiketta. Tämä lataa <b>sähkönkulutustiedoston</b> laitteellesi, jonka voit asettaa laskuriin",
      "step6": "<b>Ethän tee muutoksia</b> tiedostoon, se voi vaikuttaa laskentaan!",
      "backButton": "Takaisin laskuriin",
      "compareElectricityPrice": "Vertaa sähkön hintaa sinun Kulutustiedostosi perusteella!",
      "introText1": "Tämä palvelu laskee sinun sähkönkulutuksesi perusteella hinnan kiinteälle ja pörssisähkölle.",
      "introText2": "Lataa oma kulutus tiedostosi ",
      "setFixedPrice": "Aseta kiinteä hinta",
      "uploadAndViewResults": "Lataa tiedostosi ja tarkastele tuloksia",
      "uploadAndViewResultsBold": " Kuukausi, viikko ja päivä tasolla!",
      "fixedPrice": "Kiinteä hinta",
      "enterFixedPrice": "Syötä kiinteä hinta",
      "csvFile": "Kulutustiedosto(.csv)",
      "showSpotPrice": "Näytä pörssihinta",
      "showFixedPrice": "Näytä kiinteä hinta",
      "showConsumption": "Näytä kulutus",
      "timePeriod": "Aikaväli",
      "day": "Päivä",
      "week": "Viikko",
      "month": "Kuukausi",
      "loading": "Ladataan",
      "submit": "Hae tiedot",
      "errorFetchingData": "Tietojen hakemisessa tapahtui virhe. Yritä uudelleen.",
      "pleaseFillRequiredFields": "Täytä kaikki pakolliset kentät.",
      "previous": "Edellinen",
      "next": "Seuraava",
      "previousYear": "Edellinen vuosi",
      "nextYear": "Seuraava vuosi",
      "invalidDate": "Virheellinen päivämäärämuoto",
      "readInstructions": "Lue kulutustiedoston lataus ohjeet",
      "here": "täältä",
      "loadingAnimation": "Lataus animaatio",
      "Fingridcustomerportal": "Fingrid asiakas portaalista",
      "results": "Tulokset",
      "cheaperOption": "Sinulle Halvempi vaihtoehto on",
      "priceDifference": "Hinta ero",
      "spotElectricity": "Pörssi-sähkö",
      "timeperiodinfo": "Kulutustiedostosi mukaan aikavälillä",
      
      "totalConsumption": "Kulutus",
      "spotElectricityPrice": "Pörssi-sähköhinta",
      "fixedElectricityPrice": "Kiinteä-sähköhinta",
      "time": "Aikaväli",
      "ChartMonth": "Kuukausi",
      "ChartTime": "Aika",
      "ChartSpotPrice": "Pörssi hinta",
      "unit": " (snt/kWh) ",
      "consumption": "Kulutus",
      "Price/Consumption": "Hinta / kulutus",
      "fixedElectricity": " Kiinteä sähkö",
      "DataResource": "Pörssi hintojen lähde"

    }
  }
};

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: localStorage.getItem('i18nextLng') || 'fi',
    fallbackLng: 'fi',
    interpolation: {
      escapeValue: false
    }
  });

export default i18n;
